package cz.burios.uniql.dialect;

import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import cz.burios.uniql.metadata.ColumnMetaData;
import cz.burios.uniql.metadata.ColumnType;
import cz.burios.uniql.metadata.TableMetaData;

/** H2 dialect. JDBC schema is the SQL namespace; catalog is the database. */
public class H2Dialect implements DBDialect {
    @Override public String name() { return "h2"; }

    @Override public String quote(String name) {
        if (name == null || !name.matches("[A-Za-z_][A-Za-z0-9_$]*")) throw new IllegalArgumentException("Invalid SQL identifier: " + name);
        return "\"" + name + "\"";
    }

    @Override public String tableName(TableMetaData table) {
        if (table.schema != null && !table.schema.isBlank()) return quote(table.schema) + "." + quote(table.name);
        return quote(table.name);
    }

    @Override public ColumnType logicalType(ColumnMetaData c) {
        String nativeType = c.jdbcTypeName != null ? c.jdbcTypeName : c.type;
        if (nativeType != null) {
            String t = nativeType.toUpperCase(Locale.ROOT);
            if (t.contains("CHAR") || t.contains("VARCHAR")) return ColumnType.STRING;
            if (t.contains("CLOB") || t.contains("TEXT")) return ColumnType.TEXT;
            if (t.contains("BOOLEAN") || t.equals("BOOL")) return ColumnType.BOOLEAN;
            if (t.contains("BIGINT")) return ColumnType.LONG;
            if (t.contains("INT")) return ColumnType.INTEGER;
            if (t.contains("DECIMAL") || t.contains("NUMERIC")) return ColumnType.DECIMAL;
            if (t.contains("DOUBLE") || t.contains("REAL") || t.contains("FLOAT")) return ColumnType.DOUBLE;
            if (t.startsWith("TIMESTAMP")) return ColumnType.TIMESTAMP;
            if (t.startsWith("DATETIME")) return ColumnType.DATETIME;
            if (t.startsWith("TIME")) return ColumnType.TIME;
            if (t.startsWith("DATE")) return ColumnType.DATE;
            if (t.contains("BINARY") || t.contains("BLOB")) return ColumnType.BINARY;
        }
        return DBDialect.super.logicalType(c);
    }

    @Override public String columnDefinition(ColumnMetaData c) {
        StringBuilder sql = new StringBuilder(columnName(c.name)).append(' ').append(type(c));
        if (c.autoIncrement) sql.append(" GENERATED BY DEFAULT AS IDENTITY");
        if (!c.nullable) sql.append(" NOT NULL");
        if (c.defaultValue != null) sql.append(" DEFAULT ").append(c.defaultValue);
        return sql.toString();
    }

    /** H2 accepts one ALTER COLUMN operation per statement. */
    @Override public String alterColumn(TableMetaData table, ColumnMetaData c) {
        return "ALTER TABLE " + tableName(table) + " ALTER COLUMN " + columnName(c.name) + " " + type(c);
    }

    @Override public List<String> alterColumnStatements(TableMetaData table, ColumnMetaData c) {
        List<String> sql = new ArrayList<>();
        sql.add(alterColumn(table, c));
        sql.add("ALTER TABLE " + tableName(table) + " ALTER COLUMN " + columnName(c.name)
                + (c.nullable ? " DROP NOT NULL" : " SET NOT NULL"));
        sql.add("ALTER TABLE " + tableName(table) + " ALTER COLUMN " + columnName(c.name)
                + (c.defaultValue != null ? " SET DEFAULT " + c.defaultValue : " DROP DEFAULT"));
        return sql;
    }

    private String type(ColumnMetaData c) {
        if (c.logicalType != null) return switch (c.logicalType) {
            case STRING -> c.length > 0 ? "VARCHAR(" + c.length + ")" : "VARCHAR(255)";
            case TEXT -> "CLOB";
            case BOOLEAN -> "BOOLEAN";
            case INTEGER -> "INTEGER";
            case LONG -> "BIGINT";
            case DECIMAL -> c.precision > 0 ? "DECIMAL(" + c.precision + "," + Math.max(c.scale, 0) + ")" : "DECIMAL";
            case DOUBLE -> "DOUBLE";
            case DATE -> "DATE";
            case TIME -> "TIME";
            case DATETIME, TIMESTAMP -> "TIMESTAMP";
            case BINARY -> c.length > 0 ? "VARBINARY(" + c.length + ")" : "BLOB";
        };
        if (c.type != null && !c.type.isBlank()) return c.type.trim();
        return switch (c.jdbcType) {
            case Types.BIGINT -> "BIGINT"; case Types.INTEGER -> "INTEGER"; case Types.SMALLINT, Types.TINYINT -> "SMALLINT";
            case Types.DECIMAL, Types.NUMERIC -> "DECIMAL"; case Types.DOUBLE -> "DOUBLE"; case Types.FLOAT -> "REAL";
            case Types.BOOLEAN, Types.BIT -> "BOOLEAN"; case Types.DATE -> "DATE"; case Types.TIMESTAMP -> "TIMESTAMP"; case Types.TIME -> "TIME";
            case Types.BINARY, Types.VARBINARY, Types.LONGVARBINARY -> "BLOB"; case Types.LONGVARCHAR -> "CLOB";
            case Types.CHAR -> c.length > 0 ? "CHAR(" + c.length + ")" : "CHAR"; case Types.VARCHAR -> c.length > 0 ? "VARCHAR(" + c.length + ")" : "VARCHAR(255)";
            default -> "CLOB";
        };
    }
}
