package cz.burios.uniql.dialect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.Locale;
import cz.burios.uniql.metadata.ColumnGeneration;
import cz.burios.uniql.metadata.ColumnMetaData;
import cz.burios.uniql.metadata.ColumnType;
import cz.burios.uniql.metadata.IndexMetaData;
import cz.burios.uniql.metadata.TableMetaData;

/** PostgreSQL dialect: JDBC schema is the SQL namespace; catalog is the database. */
public class PostgreSQLDialect implements DBDialect {
 @Override public String name(){return "postgresql";}
 @Override public String tableName(TableMetaData t){return t.schema!=null&&!t.schema.isBlank()?quote(t.schema)+"."+quote(t.name):quote(t.name);}
 @Override public String quote(String n){if(n==null||!n.matches("[A-Za-z_][A-Za-z0-9_$]*"))throw new IllegalArgumentException("Invalid SQL identifier: "+n);return "\""+n+"\"";}
 @Override public void loadIndexOptions(Connection c,String catalog,String schema,String tableName,IndexMetaData index)throws SQLException{if(schema==null||schema.isBlank()||index==null||index.name==null)return;String sql="SELECT am.amname FROM pg_catalog.pg_class i JOIN pg_catalog.pg_namespace n ON n.oid=i.relnamespace JOIN pg_catalog.pg_am am ON am.oid=i.relam WHERE n.nspname=? AND i.relname=? AND i.relkind='i'";try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,schema);p.setString(2,index.name);try(ResultSet r=p.executeQuery()){if(r.next()){String method=r.getString(1);if(method!=null&&!method.isBlank())index.method(method.toUpperCase(Locale.ROOT));}}}}
 @Override public String tableOptions(TableMetaData t){if(t.params.isEmpty())return "";StringBuilder s=new StringBuilder();for(var e:t.params.entrySet())if(e.getValue()!=null){if(s.length()>0)s.append(' ');String k=e.getKey().trim().toUpperCase(Locale.ROOT);if(k.equals("TABLESPACE"))s.append("TABLESPACE ").append(e.getValue());else if(k.equals("WITH"))s.append("WITH ").append(e.getValue());else s.append(e.getKey()).append('=').append(e.getValue());}return s.length()==0?"":" "+s;}
 @Override public ColumnType logicalType(ColumnMetaData c){String n=c.jdbcTypeName!=null?c.jdbcTypeName:c.type;if(n!=null){String t=n.toUpperCase(Locale.ROOT);if(t.contains("CHAR"))return ColumnType.STRING;if(t.equals("TEXT"))return ColumnType.TEXT;if(t.equals("BOOL")||t.equals("BOOLEAN"))return ColumnType.BOOLEAN;if(t.equals("BIGINT")||t.equals("BIGSERIAL"))return ColumnType.LONG;if(t.equals("INT")||t.equals("INTEGER")||t.equals("SERIAL")||t.equals("SMALLINT")||t.equals("SMALLSERIAL"))return ColumnType.INTEGER;if(t.startsWith("NUMERIC")||t.startsWith("DECIMAL"))return ColumnType.DECIMAL;if(t.contains("DOUBLE")||t.equals("REAL"))return ColumnType.DOUBLE;if(t.startsWith("TIMESTAMP"))return ColumnType.TIMESTAMP;if(t.startsWith("TIME"))return ColumnType.TIME;if(t.startsWith("DATE"))return ColumnType.DATE;if(t.equals("BYTEA"))return ColumnType.BINARY;}return DBDialect.super.logicalType(c);}
 @Override public String columnDefinition(ColumnMetaData c){StringBuilder s=new StringBuilder(columnName(c.name)).append(' ').append(type(c));if(!c.nullable)s.append(" NOT NULL");String g=columnGeneration(c);if(!g.isBlank())s.append(' ').append(g);else if(c.defaultValue!=null)s.append(" DEFAULT ").append(c.defaultValue);return s.toString();}
 @Override public String columnGeneration(ColumnMetaData c){return switch(c.generation==null?ColumnGeneration.NONE:c.generation){case NONE->"";case INSERT_TIMESTAMP->"DEFAULT CURRENT_TIMESTAMP";case INSERT_UPDATE_TIMESTAMP->throw new UnsupportedOperationException("PostgreSQL does not support MySQL-style ON UPDATE CURRENT_TIMESTAMP; use a trigger or application lifecycle handling");};}
 @Override public String alterColumn(TableMetaData t,ColumnMetaData c){if(c.generation==ColumnGeneration.INSERT_UPDATE_TIMESTAMP)throw new UnsupportedOperationException("PostgreSQL does not support MySQL-style ON UPDATE CURRENT_TIMESTAMP");StringBuilder s=new StringBuilder("ALTER TABLE ").append(tableName(t)).append(" ALTER COLUMN ").append(columnName(c.name)).append(" TYPE ").append(type(c));s.append(", ALTER COLUMN ").append(columnName(c.name)).append(c.nullable?" DROP NOT NULL":" SET NOT NULL");if(c.defaultValue!=null||c.generation==ColumnGeneration.INSERT_TIMESTAMP)s.append(", ALTER COLUMN ").append(columnName(c.name)).append(" SET DEFAULT ").append(c.generation==ColumnGeneration.INSERT_TIMESTAMP?"CURRENT_TIMESTAMP":c.defaultValue);else s.append(", ALTER COLUMN ").append(columnName(c.name)).append(" DROP DEFAULT");return s.toString();}
 @Override public String createIndex(TableMetaData t,IndexMetaData i){StringBuilder s=new StringBuilder("CREATE ");if(i.unique)s.append("UNIQUE ");s.append("INDEX ").append(indexName(i.name)).append(" ON ").append(tableName(t));if(i.method!=null&&!i.method.isBlank())s.append(" USING ").append(i.method);s.append(" (");for(int x=0;x<i.columns.size();x++){if(x>0)s.append(", ");s.append(columnName(i.columns.get(x)));}return s.append(')').toString();}
 @Override public String dropIndex(TableMetaData t,String n){return "DROP INDEX "+indexName(n);}
 private String type(ColumnMetaData c){if(c.logicalType!=null)return switch(c.logicalType){case STRING->c.length>0?"VARCHAR("+c.length+")":"VARCHAR(255)";case TEXT->"TEXT";case BOOLEAN->"BOOLEAN";case INTEGER->c.autoIncrement?"SERIAL":"INTEGER";case LONG->c.autoIncrement?"BIGSERIAL":"BIGINT";case DECIMAL->c.precision>0?"NUMERIC("+c.precision+","+Math.max(c.scale,0)+")":"NUMERIC";case DOUBLE->"DOUBLE PRECISION";case DATE->"DATE";case TIME->"TIME";case DATETIME,TIMESTAMP->"TIMESTAMP";case BINARY->"BYTEA";};if(c.type!=null&&!c.type.isBlank())return c.type.trim();return switch(c.jdbcType){case Types.BIGINT->"BIGINT";case Types.INTEGER->"INTEGER";case Types.SMALLINT,Types.TINYINT->"SMALLINT";case Types.DECIMAL,Types.NUMERIC->"NUMERIC";case Types.DOUBLE->"DOUBLE PRECISION";case Types.FLOAT->"REAL";case Types.BOOLEAN,Types.BIT->"BOOLEAN";case Types.DATE->"DATE";case Types.TIMESTAMP->"TIMESTAMP";case Types.TIME->"TIME";case Types.BINARY,Types.VARBINARY,Types.LONGVARBINARY->"BYTEA";case Types.LONGVARCHAR->"TEXT";default->"TEXT";};}
}
