<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>cz.burios.qpx.archer</groupId>
	<artifactId>cz.burios.qpx.archer</artifactId>
	<version>26.2-SNAPSHOT</version>
	<name>cz.burios.qpx.archer</name>

	<packaging>pom</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>17</java.version>
		<spring.version>6.0.3</spring.version>
		<jakartaee-api.version>9.1.0</jakartaee-api.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<modules>
		<module>cz.burios.qpx.desktop</module>
		<module>cz.burios.uniql</module>
	</modules>

</project>
