package cz.burios.uniql.metadata;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

import cz.burios.uniql.dialect.H2Dialect;

/** Executable regression test for JDBC metadata normalization on H2. */
public class DBMetaDataH2Test {
    public static void main(String[] args) throws Exception {
        String url = "jdbc:h2:mem:uniql_metadata;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            try (Statement s = connection.createStatement()) {
                s.execute("CREATE TABLE qpx_metadata (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY, " +
                        "tenant_code VARCHAR(20) NOT NULL, " +
                        "name VARCHAR(100) NOT NULL, " +
                        "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                        "CONSTRAINT pk_qpx_metadata PRIMARY KEY (id, tenant_code))");
                s.execute("CREATE UNIQUE INDEX uk_qpx_metadata_name ON qpx_metadata(name)");
            }

            DBMetaData db = DBMetaData.load(connection);
            check("PUBLIC".equalsIgnoreCase(db.schema), "H2 schema must be detected");
            TableMetaData targeted = DBMetaData.loadTable(connection, "qpx_metadata");
            check(targeted != null, "targeted table metadata must be loaded");
            check(targeted.primaryKeys().size() == 2, "targeted metadata must include composite primary key");
            check(targeted.index("uk_qpx_metadata_name") != null, "targeted metadata must include secondary indexes");
            TableMetaData targetedBySchema = DBMetaData.loadTable(connection, "PUBLIC", "qpx_metadata");
            check(targetedBySchema != null, "schema-targeted metadata must be loaded");
            TableMetaData missing = DBMetaData.loadTable(connection, "qpx_missing");
            check(missing == null, "missing targeted table must return null");
            TableMetaData table = db.table("qpx_metadata");
            check(table != null, "table must be loaded");
            check("pk_qpx_metadata".equalsIgnoreCase(table.primaryKeyName), "primary-key name must be loaded");

            ColumnMetaData id = table.column("id");
            ColumnMetaData tenant = table.column("tenant_code");
            ColumnMetaData created = table.column("created");
            check(id != null && id.autoIncrement, "identity must be detected");
            check(id.primaryKey && id.primaryKeyPosition == 1, "first PK column and KEY_SEQ must be detected");
            check(tenant.primaryKey && tenant.primaryKeyPosition == 2, "second PK column and KEY_SEQ must be detected");
            check(created != null && created.defaultValue != null, "COLUMN_DEF must be loaded");
            check(created.generation == ColumnGeneration.NONE, "plain H2 default must not be mislabeled as timestamp generation");

            List<ColumnMetaData> keys = table.primaryKeys();
            check(keys.size() == 2, "two primary-key columns expected");
            check("id".equalsIgnoreCase(keys.get(0).name), "PK order must follow KEY_SEQ");
            check("tenant_code".equalsIgnoreCase(keys.get(1).name), "PK order must follow KEY_SEQ");

            IndexMetaData index = table.index("uk_qpx_metadata_name");
            check(index != null && index.unique, "unique secondary index must be loaded");
            check(index.columns.size() == 1 && "name".equalsIgnoreCase(index.columns.get(0)), "index column must be loaded");

            // A desired definition that only specifies portable semantics must compare
            // cleanly with the JDBC snapshot, without requiring driver-specific type text.
            DBMetaData desired = new DBMetaData();
            TableMetaData wanted = new TableMetaData("qpx_metadata")
                    .schema(table.schema)
                    .primaryKeyName("pk_qpx_metadata");
            wanted.addColumn(new ColumnMetaData("id").longType().nullable(false).primaryKey(true).autoIncrement(true));
            wanted.addColumn(new ColumnMetaData("tenant_code").string(20).nullable(false).primaryKey(true));
            wanted.addColumn(new ColumnMetaData("name").string(100).nullable(false));
            wanted.addColumn(new ColumnMetaData("created").timestamp().defaultValue(created.defaultValue));
            wanted.addIndex(new IndexMetaData("uk_qpx_metadata_name").unique(true).column("name"));
            desired.add(wanted);

            SchemaDiff diff = SchemaDiff.compare(db, desired);
            check(diff.isEmpty(), "normalized metadata should not produce a spurious migration: " + diff.toSQL(new H2Dialect()));

            try (Statement s = connection.createStatement();
                 ResultSet rs = s.executeQuery("SELECT id FROM qpx_metadata")) {
                check(!rs.next(), "metadata test table must remain empty");
            }

            System.out.println("DBMetaDataH2Test: OK");
        }
    }

    private static void check(boolean condition, String message) {
        if (!condition) throw new AssertionError(message);
    }
}
